### ISSUE TITLE
No such field "modifiers" in 1.14.3

### ISSUE THREAD

**Issue by Trophonix** [WesJD/AnvilGUI#40] opened 2019-07-16 21:01 UTC
This problem was reported by a user running paper 1.14.3

> [16:33:19 ERROR]: Could not pass event InventoryClickEvent to TradePlus v3.56
> java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers
>         at com.trophonix.tradeplus.shaded.anvilgui.version.Wrapper1_14_R1.setActiveContainerId(Wrapper1_14_R1.java:79) ~[?:?]
>         at com.trophonix.tradeplus.shaded.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:154) ~[?:?]
>         at com.trophonix.tradeplus.shaded.anvilgui.AnvilGUI.<init>(AnvilGUI.java:128) ~[?:?]
>         at com.trophonix.tradeplus.shaded.anvilgui.AnvilGUI.<init>(AnvilGUI.java:28) ~[?:?]
>         at com.trophonix.tradeplus.shaded.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:319) ~[?:?]
>         at com.trophonix.tradeplus.extras.Extra.onClick(Extra.java:112) ~[?:?]
>         at com.trophonix.tradeplus.trade.Trade.onClick(Trade.java:309) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor993.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-131]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-131]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-131]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2341) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-131]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-131]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> Caused by: java.lang.NoSuchFieldException: modifiers
>         at java.lang.Class.getField(Class.java:1703) ~[?:1.8.0_212]
>         at com.trophonix.tradeplus.shaded.anvilgui.version.Wrapper1_14_R1.setActiveContainerId(Wrapper1_14_R1.java:73) ~[?:?]
>         ... 25 more`

You can see my code here
https://github.com/Trophonix/TradePlus/blob/master/src/main/java/com/trophonix/tradeplus/extras/Extra.java#L90

**Comment by WesJD** [comment] 2019-07-16 21:28
This is a duplicate of #30

**Closed by WesJD** 2019-07-16 21:28 UTC
