### ISSUE TITLE
AnvilGUI.Builder().itemOutput() not displaying anything in 1.19.3 and 1.19.4

### ISSUE THREAD

**Issue by 2166057** [WesJD/AnvilGUI#255] opened 2023-03-24 05:01 UTC
I haven't tested for other versions but I have this simple code here that I would guess is supposed to set a LIME_WOOL in the Output Slot but somehow nothing shows up in the inventory. All the other slots are working fine.

here is my current code

    @Override
    public boolean onCommand(@NotNull CommandSender commandSender, @NotNull Command command, @NotNull String s, @NotNull String[] args) {
        if (commandSender instanceof Player viewer)
        new AnvilGUI.Builder()
                .onClose(player -> {
                    player.sendMessage("You closed the inventory.");
                })
                .onComplete((completion) -> {
                        return Arrays.asList(AnvilGUI.ResponseAction.close());
                })
                .preventClose()
                .itemLeft(new ItemStack(Material.GRAY_STAINED_GLASS_PANE))
                .itemRight(new ItemStack(Material.GRAY_STAINED_GLASS_PANE))
                .itemOutput(new ItemStack(Material.LIME_WOOL))
                .title(ChatColor.BOLD+"Test")
                .text("Change Me")
                .plugin(PremiumCore.getInstance())
                .open(viewer);
        return false;
    }

![image](https://user-images.githubusercontent.com/104145049/227428302-ff994e34-30ab-4768-bfb8-9584db849dd7.png)

I was using 1.19.3 and switched to 1.19.4 Paper

**Comment by Mr-EmPee** [comment] 2023-03-27 07:09
Duplicate of #237

**Closed** 2023-03-27 09:30 UTC
