### ISSUE TITLE
NoClassDefFoundError on Paper 1.21

### ISSUE THREAD

**Issue by FireML** [WesJD/AnvilGUI#336] opened 2024-06-27 00:45 UTC
I am using 1.9.6-SNAPSHOT and mojang mappings
https://pastes.dev/sjudUvpKn5

Intended behavior is for me to click an icon in a menu and have an Anvil GUI open, instead it throws this error.

**Comment by 0dinD** [comment] 2024-06-27 02:35
Seems like a duplicate of #330. AnvilGUI is compiled against Spigot mappings which means that your plugin will also need to be, and the plugin must be declared as such via the manifest file so that the Paper server can properly remap it. For Spigot plugins, Paper already assumes the right defaults, but if you are making a Paper plugin, you must manually configure the manifest to indicate that the Paper plugin is Spigot-mapped, [as described here](https://github.com/WesJD/AnvilGUI/issues/330#issuecomment-2138559141). Note that if you don't need the features that a Paper plugin provides, you could just make a Spigot plugin instead (the Paper API can still be used from a Spigot plugin).

**Closed** 2024-06-27 03:59 UTC
