### ISSUE TITLE
AnvilGUI does not initialize on Paper `testing/no-relocation`

### ISSUE THREAD

**Issue by datatags** [WesJD/AnvilGUI#314] opened 2024-01-31 07:46 UTC
When attempting to open an AnvilGUI on the Paper `testing/no-relocation` branch (with AnvilGUI shaded into my plugin,) an error is thrown:
```
Caused by: java.lang.ExceptionInInitializerError
        at be.isach.ultracosmetics.shaded.anvilgui.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:401) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.SubCommandRename.onExePlayer(SubCommandRename.java:31) ~[?:?]
        at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:85) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at be.isach.ultracosmetics.shaded.anvilgui.anvilgui.version.VersionMatcher.match(VersionMatcher.java:25) ~[?:?]
        at be.isach.ultracosmetics.shaded.anvilgui.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[?:?]
        at be.isach.ultracosmetics.shaded.anvilgui.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:401) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.SubCommandRename.onExePlayer(SubCommandRename.java:31) ~[?:?]
        at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:85) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```
That build of Paper can be found here: https://github.com/PaperMC/testing/releases/tag/no-relocation
Additional information: https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955
https://github.com/UltraCosmetics/UltraCosmetics/issues/153

**Comment by WesJD** [comment] 2024-03-04 01:26
Duplicate of #294

**Closed by WesJD** 2024-03-04 01:26 UTC
