### ISSUE TITLE
Weird Inventory Item Shuffling

### ISSUE THREAD

**Issue by nkomarn** [WesJD/AnvilGUI#37] opened 2019-07-13 22:44 UTC
When the anvil inventory opens, the items in my inventory always go to random slots. When you try to update the inventory, the items go back to their original place however.

Here's my inventory before opening the anvil GUI:
![image](https://user-images.githubusercontent.com/22900187/61177246-f703d380-a584-11e9-8b30-614e5377d459.png)

And after I open the anvil GUI it becomes this weird mess:
![image](https://user-images.githubusercontent.com/22900187/61177247-008d3b80-a585-11e9-8cb8-d279c9b92a4d.png)

I am using Java 11 on 1.13.2 with the latest version of Anvil GUI. This was not an issue in earlier versions.

**Comment by WesJD** [comment] 2019-07-15 18:23
The maintainers and I are unable to reproduce this bug, and the code does not move any items around in inventories. Feel free to reopen this issue with source code provided and extensive testing.

**Comment by WesJD** [comment] 2019-07-15 21:44
I have found this issue while working and it will be fixed in the next release.

**Closed** 2019-07-15 22:01 UTC
